[package]
name = "rust_rotates"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = {version = "0.4", features = ["html_reports"]}

[[bench]]
name = "benchmark"
harness = false

[dependencies]
gcd = "2.3.0"
